version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

permissions:
  - object: scripts/start.sh
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: root